<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J1CGGHU" failures="2" tests="10" name="RetryMultipleFailedTestCases" time="0.158" errors="0" timestamp="2021-02-20T11:30:22 IST">
  <testcase classname="myTests.MyTests" name="test1" time="0.013">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="myTests.MyTests" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="myTests.MyTests" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="myTests.MyTests" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTests.MyTests.test1(MyTests.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="myTests.MyTests" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="myTests.MyTests" name="test2" time="0.008">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="myTests.MyTests" name="test2" time="0.005">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="myTests.MyTests" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at myTests.MyTests.test2(MyTests.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="myTests.MyTests" name="test3" time="0.002"/>
  <testcase classname="myTests.MyTests" name="test4" time="0.003"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
